# Generated by Django 3.1.12 on 2022-11-29 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0002_auto_20221129_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='imc',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
