# Generated by Django 3.1.12 on 2022-11-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0003_patients_imc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='imc',
            new_name='result_imc',
        ),
    ]
