# Generated by Django 3.1.12 on 2022-11-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0004_auto_20221129_0243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prueba',
            new_name='Examen',
        ),
    ]
